### ISSUE TITLE
CI: test timeout on x86_64 but not on x86_32

### ISSUE THREAD

**Issue by PSRCode** [lttng/lttng-scope#40]
See https://ci.lttng.org/view/LTTng-scope/job/lttng-scope_master_build/169/

```
00:36:30 [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.643 s - in org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetArrowsTest
00:36:30 [INFO] Running org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest
00:36:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:36:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:36:32 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:36:32 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:36:32 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:36:32 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:36:32 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:36:32 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:41:31 java.lang.InterruptedException
00:41:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
00:41:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
00:41:31 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
00:41:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase$WaitForNextPulseListener.await(TimeGraphWidgetTestBase.java:215)
00:41:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.updateUI(TimeGraphWidgetTestBase.java:189)
00:41:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.seekVisibleRange(TimeGraphWidgetTestBase.java:178)
00:41:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.renderRange(TimeGraphWidgetTestBase.java:160)
00:41:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:83)
00:41:31 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:41:31 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:41:31 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:41:31 	at java.lang.reflect.Method.invoke(Method.java:498)
00:41:31 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
00:41:31 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
00:41:31 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
00:41:31 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
00:41:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
00:41:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
00:41:31 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:41:31 	at java.lang.Thread.run(Thread.java:748)
00:41:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:46:31 java.lang.InterruptedException
00:46:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
00:46:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
00:46:31 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
00:46:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase$WaitForNextPulseListener.await(TimeGraphWidgetTestBase.java:215)
00:46:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.updateUI(TimeGraphWidgetTestBase.java:189)
00:46:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.seekVisibleRange(TimeGraphWidgetTestBase.java:178)
00:46:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.renderRange(TimeGraphWidgetTestBase.java:160)
00:46:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.repaint(TimeGraphWidgetTestBase.java:148)
00:46:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:72)
00:46:31 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:46:31 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:46:31 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:46:31 	at java.lang.reflect.Method.invoke(Method.java:498)
00:46:31 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
00:46:31 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
00:46:31 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
00:46:31 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
00:46:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
00:46:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
00:46:31 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:46:31 	at java.lang.Thread.run(Thread.java:748)
00:46:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:46:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:51:31 java.lang.InterruptedException
00:51:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
00:51:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
00:51:31 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
00:51:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase$WaitForNextPulseListener.await(TimeGraphWidgetTestBase.java:215)
00:51:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.updateUI(TimeGraphWidgetTestBase.java:189)
00:51:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.seekVisibleRange(TimeGraphWidgetTestBase.java:178)
00:51:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.renderRange(TimeGraphWidgetTestBase.java:160)
00:51:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.repaint(TimeGraphWidgetTestBase.java:148)
00:51:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:72)
00:51:31 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:51:31 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:51:31 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:51:31 	at java.lang.reflect.Method.invoke(Method.java:498)
00:51:31 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
00:51:31 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
00:51:31 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
00:51:31 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
00:51:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
00:51:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
00:51:31 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:51:31 	at java.lang.Thread.run(Thread.java:748)
00:51:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:56:31 java.lang.InterruptedException
00:56:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
00:56:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
00:56:31 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
00:56:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase$WaitForNextPulseListener.await(TimeGraphWidgetTestBase.java:215)
00:56:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.updateUI(TimeGraphWidgetTestBase.java:189)
00:56:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.seekVisibleRange(TimeGraphWidgetTestBase.java:178)
00:56:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.renderRange(TimeGraphWidgetTestBase.java:160)
00:56:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.repaint(TimeGraphWidgetTestBase.java:148)
00:56:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:72)
00:56:31 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:56:31 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:56:31 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:56:31 	at java.lang.reflect.Method.invoke(Method.java:498)
00:56:31 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
00:56:31 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
00:56:31 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
00:56:31 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
00:56:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
00:56:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
00:56:31 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:56:31 	at java.lang.Thread.run(Thread.java:748)
00:56:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
00:56:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
01:01:31 java.lang.InterruptedException
01:01:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
01:01:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
01:01:31 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
01:01:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase$WaitForNextPulseListener.await(TimeGraphWidgetTestBase.java:215)
01:01:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.updateUI(TimeGraphWidgetTestBase.java:189)
01:01:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.seekVisibleRange(TimeGraphWidgetTestBase.java:178)
01:01:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.renderRange(TimeGraphWidgetTestBase.java:160)
01:01:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.repaint(TimeGraphWidgetTestBase.java:148)
01:01:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:72)
01:01:31 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:01:31 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:01:31 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:01:31 	at java.lang.reflect.Method.invoke(Method.java:498)
01:01:31 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
01:01:31 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
01:01:31 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
01:01:31 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
01:01:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
01:01:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
01:01:31 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01:01:31 	at java.lang.Thread.run(Thread.java:748)
01:01:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
01:01:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
01:06:31 java.lang.InterruptedException
01:06:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
01:06:31 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
01:06:31 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase$WaitForNextPulseListener.await(TimeGraphWidgetTestBase.java:215)
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.updateUI(TimeGraphWidgetTestBase.java:189)
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.seekVisibleRange(TimeGraphWidgetTestBase.java:178)
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.renderRange(TimeGraphWidgetTestBase.java:160)
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetTestBase.repaint(TimeGraphWidgetTestBase.java:148)
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:72)
01:06:31 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:31 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:31 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:31 	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:31 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
01:06:31 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
01:06:31 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
01:06:31 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
01:06:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
01:06:31 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
01:06:31 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01:06:31 	at java.lang.Thread.run(Thread.java:748)
01:06:31 Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
01:06:31 [ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 1,801.219 s <<< FAILURE! - in org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest
01:06:31 [ERROR] testStatesResolution[resolution: 1](org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest)  Time elapsed: 300.011 s  <<< ERROR!
01:06:31 org.junit.runners.model.TestTimedOutException: test timed out after 5 minutes
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:83)
01:06:31 
01:06:31 [ERROR] testStatesResolution[resolution: 2](org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest)  Time elapsed: 300.003 s  <<< ERROR!
01:06:31 org.junit.runners.model.TestTimedOutException: test timed out after 5 minutes
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:72)
01:06:31 
01:06:31 [ERROR] testStatesResolution[resolution: 5](org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest)  Time elapsed: 300.001 s  <<< ERROR!
01:06:31 org.junit.runners.model.TestTimedOutException: test timed out after 5 minutes
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:72)
01:06:31 
01:06:31 [ERROR] testStatesResolution[resolution: 10](org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest)  Time elapsed: 300.003 s  <<< ERROR!
01:06:31 org.junit.runners.model.TestTimedOutException: test timed out after 5 minutes
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:72)
01:06:31 
01:06:31 [ERROR] testStatesResolution[resolution: 50](org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest)  Time elapsed: 300.003 s  <<< ERROR!
01:06:31 org.junit.runners.model.TestTimedOutException: test timed out after 5 minutes
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:72)
01:06:31 
01:06:31 [ERROR] testStatesResolution[resolution: 100](org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest)  Time elapsed: 300.008 s  <<< ERROR!
01:06:31 org.junit.runners.model.TestTimedOutException: test timed out after 5 minutes
01:06:31 	at org.lttng.scope.views.timeline.widgets.timegraph.TimeGraphWidgetStatesTest.testStatesResolution(TimeGraphWidgetStatesTest.java:72)
01:06:31 
```

**Comment by alexmonthy** [comment]
It runs fine on x32 and on [Travis](https://travis-ci.org/lttng/lttng-scope/builds/314957785) so it looks like something is wrong/weird with the environment.

I'll try to add something so that we can get the callstack of these `java.lang.ArrayIndexOutOfBoundsException`.

**Comment by PSRCode** [comment]
Well it is a good time to get the callstack running.
I will look into the env settings. And what changed lately.
